### ISSUE TITLE
Не устанавливается плагин. Проблемы с husky.

### ISSUE THREAD

**Issue by exocornet** [ivliag/handy-svg#1]
Здравствуйте. Решил использовать ваш плагин и установить в свой проект. Но ни чего не вышло. Жалуется на конфликт с husky. Могли бы подсказать в чем может быть данная проблема? И как ее можно устранить буду очень благодарен. За ранее спасибо.

версия Node.js - 16.16.0
![handy-svg](https://user-images.githubusercontent.com/57918887/180753712-f18839c9-1366-47a3-8212-cc1a98524737.jpg)

**Comment by ivliag** [comment]
Починил в версии 1.0.6
Спасибо!

**Comment by exocornet** [comment]
> Починил в версии 1.0.6 Спасибо!

Спасибо. Большое!
